DROP TABLE IF EXISTS BUGS;
DROP TABLE IF EXISTS USERS;
DROP SEQUENCE IF EXISTS bug_seq;

CREATE TABLE USERS (
  login_id VARCHAR(20) PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  email VARCHAR(250) DEFAULT NULL
);

CREATE TABLE BUGS (
  bug_id VARCHAR(20) PRIMARY KEY,
  title VARCHAR(100) NOT NULL,
  description VARCHAR(250) DEFAULT NULL,
  status VARCHAR(20) NOT NULL,
  severity VARCHAR(20) NOT NULL,
  assignee VARCHAR(20) NULL,
  reporter VARCHAR(20) NOT NULL,
  created_at TIMESTAMP NOT NULL,
  updated_at TIMESTAMP NOT NULL,
  closed_at TIMESTAMP  NULL,
  deleted BOOLEAN DEFAULT false
);

ALTER TABLE BUGS
ADD FOREIGN KEY (assignee)
REFERENCES USERS(login_id);

ALTER TABLE BUGS
ADD FOREIGN KEY (reporter)
REFERENCES USERS(login_id);

CREATE SEQUENCE BUG_SEQ
MINVALUE 1
MAXVALUE 999999999
INCREMENT BY 1
START WITH 1
NOCACHE
NOCYCLE;